### ISSUE TITLE
Kernel doesn't respond to kernel_info_requests

### ISSUE THREAD

**Issue by Symbolics** [yitzchak/common-lisp-jupyter#77]
Just updated today to get the markdown render changes and get the following. The time out value is `c.MappingKernelManager.kernel_info_timeout=600` (10 minutes!), but I don' think that's the problem, since you can see that SBCL does start (after about 2 1/2 minutes).

I _think_ this is independent of the `shasht` error. I don't have the `shasht` repo on my system, so this would be coming from Quicklisp.

Does anything else, either on the lisp side or python side need to be upgraded as well? I don't see `yason` in the ASD file any longer, so it looks like I'll have to rewrite anything that was depending on that code, unless it's safe to import `yason` along side of CLJ. Are there any release notes?

```
PS S:\src\IPS\notebooks> jupyter-console --kernel=common-lisp
This is SBCL 2.0.10.7-1968e18ce, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
Traceback (most recent call last):
  File "C:\Users\foo\miniconda3\lib\site-packages\jupyter_console\ptshell.py", line 433, in init_kernel_info
    reply = self.client.get_shell_msg(timeout=1)
  File "C:\Users\foo\miniconda3\lib\site-packages\jupyter_client\client.py", line 78, in get_shell_msg
    return self.shell_channel.get_msg(*args, **kwargs)
  File "C:\Users\foo\miniconda3\lib\site-packages\jupyter_client\blocking\channels.py", line 54, in get_msg
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\foo\miniconda3\Scripts\jupyter-console-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\foo\miniconda3\lib\site-packages\jupyter_core\application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\foo\miniconda3\lib\site-packages\traitlets\config\application.py", line 844, in launch_instance
    app.initialize(argv)
  File "C:\Users\foo\miniconda3\lib\site-packages\traitlets\config\application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "C:\Users\foo\miniconda3\lib\site-packages\jupyter_console\app.py", line 137, in initialize
    self.init_shell()
  File "C:\Users\foo\miniconda3\lib\site-packages\jupyter_console\app.py", line 107, in init_shell
    self.shell = ZMQTerminalInteractiveShell.instance(parent=self,
  File "C:\Users\foo\miniconda3\lib\site-packages\traitlets\config\configurable.py", line 537, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\foo\miniconda3\lib\site-packages\jupyter_console\ptshell.py", line 351, in __init__
    self.init_kernel_info()
  File "C:\Users\foo\miniconda3\lib\site-packages\jupyter_console\ptshell.py", line 436, in init_kernel_info
    raise RuntimeError("Kernel didn't respond to kernel_info_request") from e
RuntimeError: Kernel didn't respond to kernel_info_request
PS S:\src\IPS\notebooks> To load "common-lisp-jupyter":
  Load 1 ASDF system:
    common-lisp-jupyter
; Loading "common-lisp-jupyter"
..................................................
[package jupyter]
debugger invoked on a SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread
#<THREAD "main thread" RUNNING {1002300003}>:
  no symbol named "MAKE-OBJECT" in "SHASHT"

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE                     ] INTERN it.
  1: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "common-lisp-jupyter" "src" "packages">.
  2: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "common-lisp-jupyter" "src" "packages">
                                     as having been successful.
  3:                                 Retry ASDF operation.
  4: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  5:                                 Retry ASDF operation.
  6:                                 Retry ASDF operation after resetting the
                                     configuration.
  7: [ABORT                        ] Give up on "common-lisp-jupyter"
  8: [REGISTER-LOCAL-PROJECTS      ] Register local projects and try again.
  9:                                 Ignore runtime option --eval "(ql:quickload :common-lisp-jupyter)".
 10:                                 Skip rest of --eval and --load options.
 11:                                 Skip to toplevel READ/EVAL/PRINT loop.
 12: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(SB-IMPL::FIND-OR-MAKE-SYMBOL "MAKE-OBJECT" #<PACKAGE "SHASHT">)
0]
;
; compilation unit aborted
;   caught 2 fatal ERROR conditions

debugger invoked on a SB-INT:SIMPLE-READER-PACKAGE-ERROR in thread
#<THREAD "main thread" RUNNING {1002300003}>:
  Package JUPYTER does not exist.

    Stream: #<dynamic-extent STRING-INPUT-STREAM (unavailable) from "(jupyter...">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE ] Use the current package, COMMON-LISP-USER.
  1: [RETRY    ] Retry finding the package.
  2: [USE-VALUE] Specify a different package
  3: [UNINTERN ] Read the symbol as uninterned.
  4: [SYMBOL   ] Specify a symbol to return
  5:             Ignore runtime option --eval "(jupyter:run-kernel 'common-lisp-jupyter:kernel #\"C:\\Users\\foo\\AppData\\Roaming\\jupyter\\runtime\\kernel-61460.json\")".
  6: [ABORT    ] Skip rest of --eval and --load options.
  7:             Skip to toplevel READ/EVAL/PRINT loop.
  8: [EXIT     ] Exit SBCL (calling #'EXIT, killing the process).

(SB-IMPL::READER-FIND-PACKAGE "JUPYTER" #<SB-IMPL::STRING-INPUT-STREAM {7FF5D3}> T)
0]
CL-USER(1):
```

**Comment by yitzchak** [comment]
There are changes to shasht also. Until Quicklisp updates you will need a copy of that repo. 

You can use other JSON libraries in your own code. They shouldn't interfere,

**Comment by Symbolics** [comment]
Okay, I've got Shasht, and moved a bit farther along, but still no joy. Looks like a problem in jupyter-convert in a dispatch function:

```
PS S:\src\common-lisp-jupyter> jupyter-console --kernel=common-lisp
This is SBCL 2.0.10.7-1968e18ce, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
Traceback (most recent call last):
  File "C:\Users\foo\miniconda3\lib\site-packages\jupyter_console\ptshell.py", line 433, in init_kernel_info
    reply = self.client.get_shell_msg(timeout=1)
  File "C:\Users\foo\miniconda3\lib\site-packages\jupyter_client\client.py", line 78, in get_shell_msg
    return self.shell_channel.get_msg(*args, **kwargs)
  File "C:\Users\foo\miniconda3\lib\site-packages\jupyter_client\blocking\channels.py", line 54, in get_msg
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\foo\miniconda3\Scripts\jupyter-console-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\foo\miniconda3\lib\site-packages\jupyter_core\application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\foo\miniconda3\lib\site-packages\traitlets\config\application.py", line 844, in launch_instance
    app.initialize(argv)
  File "C:\Users\foo\miniconda3\lib\site-packages\traitlets\config\application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "C:\Users\foo\miniconda3\lib\site-packages\jupyter_console\app.py", line 137, in initialize
    self.init_shell()
  File "C:\Users\foo\miniconda3\lib\site-packages\jupyter_console\app.py", line 107, in init_shell
    self.shell = ZMQTerminalInteractiveShell.instance(parent=self,
  File "C:\Users\foo\miniconda3\lib\site-packages\traitlets\config\configurable.py", line 537, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\foo\miniconda3\lib\site-packages\jupyter_console\ptshell.py", line 351, in __init__
    self.init_kernel_info()
  File "C:\Users\foo\miniconda3\lib\site-packages\jupyter_console\ptshell.py", line 436, in init_kernel_info
    raise RuntimeError("Kernel didn't respond to kernel_info_request") from e
RuntimeError: Kernel didn't respond to kernel_info_request
PS S:\src\common-lisp-jupyter> To load "common-lisp-jupyter":
  Load 1 ASDF system:
    common-lisp-jupyter
; Loading "common-lisp-jupyter"
..................................................
[package shasht]..................................
[package jupyter].................................
[package jupyter/markdown-formatter]..............
[package jupyter-widgets].........................
[package common-lisp-jupyter].....................
[package jupyter-convert].........................
.........................

debugger invoked on a SB-INT:SIMPLE-READER-ERROR in thread
#<THREAD "main thread" RUNNING {1002310003}>:
  no dispatch function defined for #\"

    Stream: #<dynamic-extent STRING-INPUT-STREAM (unavailable) from "(jupyter...">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE] Ignore runtime option --eval "(jupyter:run-kernel 'common-lisp-jupyter:kernel #\"C:\\Users\\foo\\AppData\\Roaming\\jupyter\\runtime\\kernel-60936.json\")".
  1: [ABORT   ] Skip rest of --eval and --load options.
  2:            Skip to toplevel READ/EVAL/PRINT loop.
  3: [EXIT    ] Exit SBCL (calling #'EXIT, killing the process).

(SB-IMPL::READ-MAYBE-NOTHING #<SB-IMPL::STRING-INPUT-STREAM {7FF5D3}> #\#)
```

**Comment by yitzchak** [comment]
Yeah, I should probably put a comment in the README about that. I changed the command line in the kernel spec file. You need to do your `(cl-jupyter:install)` step again.

**Comment by Symbolics** [comment]
I've done the install again, confirmed the `kernel.json` contents and am encountering the same issue mentioned in #65, so I'll close this issue and pick it up there for continuity.
