### ISSUE TITLE
Error starting kernel

### ISSUE THREAD

**Issue by BaseBeginner** [yitzchak/common-lisp-jupyter#96]
Hello. I followed the instructions to installing on this page:https://yitzchak.github.io/common-lisp-jupyter/install

Specifically, I followed the instructions in the section: **Installing via Roswell**. 

When I run the command `jupyter console --kernel=common-lisp
`, I get the following error message:

```
[ZMQTerminalIPythonApp] ERROR | Failed to run command:
['cl-jupyter', '/Users/kofiowusu/Library/Jupyter/runtime/kernel-65898.json']
    PATH='/usr/local/opt/tomcat@9/bin:/usr/local/opt/bzip2/bin:/Users/kofiowusu/.opam/default/bin:/Library/TeX/texbin:/Library/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin:/Users/kofiowusu/.gvm/bin:/usr/local/texlive/2017/bin/x86_64-darwin:/Users/kofiowusu/.rbenv/shims:/Users/kofiowusu/.pyenv/shims:/Users/kofiowusu/.nvm/versions/node/v18.9.0/bin:/Users/kofiowusu/.phpenv/shims:/Users/kofiowusu/.phpenv/bin:/usr/local/opt/bison/bin:/Users/kofiowusu/.jenv/shims:/Users/kofiowusu/.jenv/bin:/usr/local/opt/tcl-tk/bin:/usr/local/anaconda3/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/kofiowusu/.cargo/bin:/Users/kofiowusu/.cabal/bin:/Users/kofiowusu/.ghcup/bin:/Users/kofiowusu/.local/bin:/Library/TeX/texbin'
    with kwargs:
{'stdin': -1, 'stdout': None, 'stderr': None, 'cwd': None, 'start_new_session': True}

Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/jupyter-console", line 10, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/lib/python3.9/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.initialize(argv)
  File "/usr/local/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 88, in inner
    return method(app, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.9/site-packages/jupyter_console/app.py", line 136, in initialize
    self.init_shell()
  File "/usr/local/anaconda3/lib/python3.9/site-packages/jupyter_console/app.py", line 103, in init_shell
    JupyterConsoleApp.initialize(self)
  File "/usr/local/anaconda3/lib/python3.9/site-packages/jupyter_client/consoleapp.py", line 343, in initialize
    self.init_kernel_manager()
  File "/usr/local/anaconda3/lib/python3.9/site-packages/jupyter_client/consoleapp.py", line 295, in init_kernel_manager
    self.kernel_manager.start_kernel(**kwargs)
  File "/usr/local/anaconda3/lib/python3.9/site-packages/jupyter_client/manager.py", line 341, in start_kernel
    self.kernel = self._launch_kernel(kernel_cmd, **kw)
  File "/usr/local/anaconda3/lib/python3.9/site-packages/jupyter_client/manager.py", line 249, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/usr/local/anaconda3/lib/python3.9/site-packages/jupyter_client/launcher.py", line 132, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/usr/local/anaconda3/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/anaconda3/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cl-jupyter'
```
And when I open a new notebook, I get this error message: `[Errno 2] No such file or directory: 'cl-jupyter'`

Any help would be appreciated. Thanks.

**Comment by BaseBeginner** [comment]
Nevermind, I fixed it. Forgot to export the path.
